name: Deploy Clustering Tool

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test application
      run: |
        python -c "import app; print('✅ App imports successfully')"
        python -c "import clustering_tool; print('✅ Clustering tool imports successfully')"

  deploy-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t clustering-tool .
        echo "✅ Docker image built successfully"
    
    - name: Test Docker container
      run: |
        docker run -d -p 5000:5000 --name test-container clustering-tool
        sleep 10
        curl -f http://localhost:5000 || exit 1
        docker stop test-container
        docker rm test-container
        echo "✅ Docker container tested successfully"